/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PilatesClass = IDL.Record({
  'duration_minutes' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const StudioInfo = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'contact_email' : IDL.Text,
  'classes' : IDL.Vec(PilatesClass),
});

export const idlService = IDL.Service({
  'getAllClasses' : IDL.Func([], [IDL.Vec(PilatesClass)], ['query']),
  'getClassByName' : IDL.Func([IDL.Text], [PilatesClass], ['query']),
  'getStudioInfo' : IDL.Func([], [StudioInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PilatesClass = IDL.Record({
    'duration_minutes' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const StudioInfo = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'contact_email' : IDL.Text,
    'classes' : IDL.Vec(PilatesClass),
  });
  
  return IDL.Service({
    'getAllClasses' : IDL.Func([], [IDL.Vec(PilatesClass)], ['query']),
    'getClassByName' : IDL.Func([IDL.Text], [PilatesClass], ['query']),
    'getStudioInfo' : IDL.Func([], [StudioInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };